export const majors = [
  "Art & Design: Games + Playable Media B.A.",
  "Environmental Studies B.A.",
  "Physics B.S.",
  "Music B.M.",
  "Art and Design: Games and Playable Media B.A.",
  "Computer Science B.A.",
  "Education, Democracy, and Justice B.A.",
  "Chemistry B.A.",
  "Computer Engineering B.S.",
  "Literature B.A.",
  "Chemistry B.S.",
  "Anthropology Combined Major B.A.",
  "Network and Digital Technology B.A.",
  "Economics Combined Major B.A.",
  "Computer Science: Computer Game Design B.S.",
  "Molecular, Cell, and Developmental Biology B.S.",
  "Sociology Combined B.A.",
  "Italian Studies B.A.",
  "Classical Studies B.A.",
  "Film and Digital Media B.A.",
  "Politics Combined B.A.",
  "Economics B.A.",
  "Mathematics B.A.",
  "Mathematics Theory and Computation B.S.",
  "Earth Sciences B.S.",
  "Biochemistry and Molecular Biology B.S.",
  "Anthropology B.A.",
  "Linguistics B.A.",
  "Applied Linguistics and Multilingualism B.A.",
  "Biotechnology B.A.",
  "Community Studies B.A.",
  "Science Education B.S.",
  "Legal Studies B.A.",
  "Plant Sciences B.S.",
  "Physics (Astrophysics) B.S.",
  "Earth Sciences Combined Major B.A.",
  "Marine Biology B.S.",
  "Language Studies B.A.",
  "Human Biology B.S.",
  "Art B.A.",
  "Ecology and Evolution B.S.",
  "Robotics Engineering B.S.",
  "Microbiology B.S.",
  "Jewish Studies B.A.",
  "History of Art and Visual Culture B.A.",
  "Music B.A.",
  "Electrical Engineering B.S.",
  "Global and Community Health B.S.",
  "Spanish Studies B.A.",
  "History B.A.",
  "Environmental Sciences B.S.",
  "Latin American and Latino Studies B.A.",
  "Applied Physics B.S.",
  "Psychology B.A.",
  "Computer Science B.S.",
  "Neuroscience B.S.",
  "Biology Combined Major B.A.",
  "Mathematics B.S.",
  "Mathematics Education B.A.",
  "Mathematics Combined B.A.",
  "Critical Race and Ethnic Studies B.A.",
  "Global and Community Health B.A.",
  "Biology B.S.",
  "Human Biology B.S. (Discontinued)",
  "Cognitive Science B.S.",
  "Sociology B.A.",
  "Technology and Information Management B.S.",
  "Agroecology B.A.",
  "Applied Mathematics B.S.",
  "Biology B.A.",
  "Global Economics B.A.",
  "Feminist Studies B.A.",
  "Theater Arts B.A.",
  "Business Management Economics B.A.",
  "Biomolecular Engineering and Bioinformatics B.S.",
  "Politics B.A.",
  "Philosophy B.A.",
];
export const minors = [
  "Anthropology",
  "Applied Mathematics",
  "Assistive Technology",
  "Astrophysics",
  "Bioelectronics and Biophotonics",
  "Bioinformatics",
  "Biology",
  "Black Studies",
  "Chemistry",
  "Classical Studies",
  "Computer Engineering",
  "Computer Science",
  "Dance",
  "Earth Sciences",
  "East Asian Studies",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Electronic Music",
  "Film and Digital Media",
  "Global Information Social Enterprise Studies",
  "History of Art and Visual Culture",
  "History",
  "Italian Studies",
  "Jazz, Spontaneous Composition and Improvisation",
  "Jewish Studies",
  "Latin American/Latino Studies",
  "Language Studies",
  "Legal Studies",
  "Linguistics",
  "Literature",
  "Mathematics",
  "Middle Eastern and North African Studies",
  "Philosophy",
  "Physics",
  "Politics",
  "Statistics",
  "Science, Technology, Engineering, and Mathematics Education",
  "Spanish Studies",
  "Sustainability Studies",
  "Technology and Information Management",
  "Theater Arts",
  "Western Art Music",
];

export const years = ["2020-2021", "2021-2022", "2022-2023", "2023-2024"];
