import { Args, Query, Resolver } from "type-graphql";

import { Course, SingleQueryInput } from "./schema";
import { CourseService } from "./service";

/**
 * CourseResolver is a Resolver class that provides custom functionality for
 * courses, which cannot be generated by Prisma
 */
@Resolver()
export class CourseResolver {
  /**
   * Return a `Course` instance that matches the `department` and `number` in `input`
   * @param input a QueryInput instance
   * @returns a `Course` instance
   */
  @Query(() => Course)
  async courseBy(@Args() input: SingleQueryInput): Promise<Course | null> {
    return await new CourseService().courseBy(input);
  }
}
