import { CourseService } from "./service";
import { Arg, Mutation, Query, Resolver } from "type-graphql";
import { Major, MajorInput } from "./schema";

/**
 * CourseResolver is a Resolver class that provides custom functionality for
 * courses, which cannot be generated by Prisma
 */
@Resolver()
export class MajorResolver {
  /**
   * @returns a unique `Major` associated with a userId
   */
  @Query(() => Major)
  async getMajor(@Arg("userId") userId: string): Promise<Major | null> {
    return await new CourseService().getMajor(userId);
  }

  /**
   * Updates or creates a new major and associates it with a userId
   * @param major is a type containing a students' major information
   * @returns the updated or created `Major`
   */
  @Mutation(() => Major)
  async upsertMajor(
    @Arg("userId") userId: string,
    @Arg("major") major: MajorInput,
  ): Promise<Major> {
    return await new CourseService().upsertMajor(userId, major);
  }
}
