import { MajorVerificationContext } from "@/app/contexts/MajorVerificationProvider";
import { useContext } from "react";
import { CheckCircle, Cancel } from "@mui/icons-material";

export default function MajorProgress() {
  const { majorIsVerified, errors } = useContext(MajorVerificationContext);

  // NEEDS TO BE CLEANED UP, was quickly generated by github copilot

  return (
    <div className="flex justify-between">
      <div className="flex-initial">
        <h2 className="text-2xl font-medium">Major Progress</h2>
      </div>
      <div className="flex-initial">
        {majorIsVerified ? (
          <div className="flex items-center space-x-2">
            <div className="text-green-500">
              <CheckCircle />
            </div>
            <div className="text-green-500">Verified</div>
          </div>
        ) : (
          <div className="flex items-center space-x-2">
            <div className="text-red-500">
              <Cancel />
            </div>
            <div className="text-red-500">Not Verified</div>
            <div>{errors}</div>
          </div>
        )}
      </div>
    </div>
  );
}
