query GetCourse($courseName: String, $courseDepartment: String, $courseNumber: String, $courseCredits: Float) {
  course(name: $courseName, department: $courseDepartment, number: $courseNumber, credits: $courseCredits) {
    id
    name
    department
    number
    credits
  }
}
