name: CI/CD Pipeline

on: [push]

env:
  POSTGRES_PRISMA_URL: "postgres://postgres:postgres@localhost:5432/float?schema=public"
  # Mock values for testing
  LOGFLARE_API_KEY: "github-actions"
  LOGFLARE_SOURCE_TOKEN: "github-actions"
  PAUSE_TOKEN: "github-actions"
  WEBHOOK_SECRET: "github-actions"
  PROJECT_ID: "github-actions"
  TEAM_ID: "github-actions"
  GOOGLE_CLIENT_ID: "github-actions"
  GOOGLE_CLIENT_SECRET: "github-actions"
  NEXTAUTH_SECRET: "github-actions"

jobs:
  print-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Print Git Commit
        run: echo ${{ github.sha}}

  format:
    runs-on: ubuntu-latest
    needs: print-commit
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "21"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check Format
        run: yarn format:check

  lint:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "21"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

  build-and-test:
    runs-on: ubuntu-latest
    needs: lint
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_DB: float
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      POSTGRES_PRISMA_URL: "postgres://postgres:postgres@localhost:5432/float?schema=public"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "21"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Postgres DB
        run: |
          npx prisma generate
          npx prisma migrate deploy

      - name: Run Jest Tests
        run: yarn test
