name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_DB: float
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      POSTGRES_PRISMA_URL: "postgres://postgres:postgres@localhost:5432/float?schema=public"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Build
        run: |
          npm ci
          npx prisma generate
          npm run build

      - name: Populate Postgres Database
        run: |
          npx prisma db push
          npx prisma db seed

      - name: Run Jest Tests
        run: npm run test
      
      - name: Run Cypress Tests
        run: npm run e2e:headless
